# Generated by Django 6.0.2 on 2026-03-15 10:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_song_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikedPlaylistName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(default='My Liked Songs', max_length=100)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liked_playlist_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
