# Generated by Django 6.0.2 on 2026-03-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_userlikedplaylistname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikedplaylistname',
            name='last_updated',
        ),
    ]
