# Generated by Django 6.0.2 on 2026-04-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_userlikedplaylistname_delete_userplaylistname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_type',
            field=models.CharField(choices=[('playlist1', 'PlayList-1'), ('playlist2', 'The New Wave'), ('artists', 'Artists'), ('top_charts', 'The Top Charts'), ('New_section', 'Industry Pulse')], default='playlist1', max_length=50),
        ),
    ]
